[package]
name = "bill_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "23.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.0"
chrono = "0.4.41"
